###Artistes
- artiste: PNL
  prenom: Nabil / Tarik
  naiss: 25 avril 1989 / 26 décembre 1986
- artiste: JUL
  prenom: Julien Mari
  naiss: 14 janvier 1990
- artiste: Wejdene
  prenom: Wejdene
  naiss: Inconnue
###Albums
- titre: La Machine
  nomArtiste: Jul
  nbDeSons: 30
  genre: Rap
- titre: Deux frères
  nomArtiste: PNL
  nbDeSons: 16
- titre: "16"
  nomArtiste: Wejdene
  nbDeSons: 11