###Albums
- id: 1
  titre: "La machine"
  nomArtiste: "Jul"
  nombreSons: 16
  genre: "Rap"
  img: "machine.png"
###Artiste
- id: 1
  nomDeScene: "Jul"
  prenom: "Julien Mari"
  dateNaiss: "14 janvier 1990"
  img: "jul.png"